### PR TITLE
Improve Keras Tuner Documentation

### PR DESCRIPTION
**Pull request by omalleyt12**
Mostly added docstrings

Still need to add docstrings for HyperModel, and to add more examples and tutorials for advanced use cases

I also filed a few bugs I found in the keras-autodoc.

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
I would recommend avoiding renaming `kerastuner_docs` -> `docs`. This is because, if we have multiple keras projects installed with `pip install -e ./` for development, we'll en up with multiple python packages named `docs`.  Then we won't be able to import them in the test suite, if we want to test our documentation.

**Comment by gabrieldemarmiesse** [comment]
Btw, thanks for the issues opened. I'll look into them.

**Comment by omalleyt12** [comment]
@gabrieldemarmiesse Thanks! And thanks for bumping the version of `keras-autodoc` used. I changed the doc directory back to `kerastuner_docs`

**Comment by fchollet** [comment]
> I would recommend avoiding renaming kerastuner_docs -> docs. This is because, if we have multiple keras projects installed with pip install -e ./ for development, we'll en up with multiple python packages named docs.

In that case the issue is with using `pip install -e ./`, not with the name of the folder. It's sensible for the docs to live in a `docs/` directory (across multiple repos), much like tests live in a `tests/` directory, etc.

**Comment by gabrieldemarmiesse** [comment]
Well, sure, It's a minor thing, I can work around that.

**Comment by omalleyt12** [comment]
Thanks for the review!

**Pull request merged**
