### PR TITLE
Added types, compatible with py2.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
This is a follow-up on https://github.com/keras-team/keras-tuner/pull/163

I added types, but in a way compatible with python 2.7. See https://mypy.readthedocs.io/en/latest/python2.html for details on typing python 2 code.

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Unrelated failure. Please merge #186 first.

**Comment by omalleyt12** [comment]
Closed / reopened to retrigger tests

**Comment by omalleyt12** [comment]
@gabrieldemarmiesse Thanks for the PR! Should we also include `typing` in dependencies for keras-tuner, or is this built-in?

**Comment by gabrieldemarmiesse** [comment]
Good question. I need to check.

**Comment by gabrieldemarmiesse** [comment]
Ok, so the bottom line is that typing is build-in in python 3.5+ and that it's not build in python 2.7. I need to add it to the setup.py.

**Comment by gabrieldemarmiesse** [comment]
As said in the project description https://pypi.org/project/typing/: 

>  in Python 3.5 and later, the typing module lives in the stdlib, and installing this package has NO EFFECT. 

So the typing package is going to be installed in both python 2 and 3, but in python 3 it's going to have no effect. This is what we want.

**Comment by haifeng-jin** [comment]
no longer supporting py2

**Pull request closed without merging**
