### PR TITLE
Rename kerastuner to keras_tuner

### LINKED ISSUE #540: Rename the import name to `keras_tuner` while keep but deprecate warning the current import name of `kerastuner`

### PR DESCRIPTION
**Pull request by haifeng-jin**
Change the import name of Keras Tuner from `kerastuner` to `keras_tuner`.
The old name is still supported, but throw a deprecation warning.
This feature is implemented with the [kt-legacy repo](https://github.com/haifeng-jin/kt-legacy).
A [new test](https://github.com/keras-team/keras-tuner/pull/546/files#diff-a42be837a12c12ed6c63cac039f73eeaff47bb52622cc6d60db0f0ed849ef42fR1-R14) is added to ensure it works.
The warning message is [here](https://github.com/haifeng-jin/kt-legacy/blob/main/kerastuner/__init__.py)

resolves #540

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR!

> This feature is implemented with the kt-legacy repo.

How does it work?

**Comment by haifeng-jin** [comment]
> Thanks for the PR!
> 
> > This feature is implemented with the kt-legacy repo.
> 
> How does it work?

@fchollet 
It is used as a dependency of Keras Tuner.
When installing Keras Tuner, kt-legacy will be installed.

Its import name is `kerastuner`.
It imports everything from `keras_tuner` to put under itself, i.e., `kerastuner`.
Threrefore, importing `kerastuner` is the same as import `keras_tuner`.

It throws a warning in its `__init__.py`.
Thus, when people import `kerastuner`, the warning will be shown.

The code is [here](https://github.com/haifeng-jin/kt-legacy/blob/main/kerastuner/__init__.py#L1-L8)

**Comment by fchollet** [comment]
Can you do e.g. `from kerastuner.tuners import RandomSearch`?

**Comment by haifeng-jin** [comment]
> Can you do e.g. `from kerastuner.tuners import RandomSearch`?

@fchollet 
No. I guess we will have to build a similar directory structure to enable this use case.

**Comment by fchollet** [comment]
> No. I guess we will have to build a similar directory structure to enable this use case.

Ok, let's do that. We only have a few directories, and we just need one line per directory (`from ... import *`)

**Comment by haifeng-jin** [comment]
> Ok, let's do that. We only have a few directories, and we just need one line per directory (`from ... import *`)
@fchollet 
I have updated it to support the use case.
This [notebook](https://colab.research.google.com/drive/1SGcP1iVmB7bRBbrfIKXoCMNARdtK5CIo?resourcekey=0-9ybiYdWLRNxPl_HILsORyw&usp=sharing) shows the usages of the different ways of the imports.
The tests are enhanced to cover a wider range of import usages. [link](https://github.com/keras-team/keras-tuner/pull/546/files#diff-a42be837a12c12ed6c63cac039f73eeaff47bb52622cc6d60db0f0ed849ef42fR4)

**Review by fchollet — APPROVED** [review]
Excellent -- thank you!

**Pull request merged**
