### PR TITLE
fix: :rotating_light: Fix `flake8` warnings

### LINKED ISSUE #778: Flake8 exceptions are incomplete
**Describe the bug**

Currently, `git commits` can be rejected by getting the following log message.

```log
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - -S
Skipped 7 files
./keras_tuner/engine/trial.py:46:19: N805 first argument of a method should be named 'self'
./keras_tuner/engine/trial.py:65:21: N805 first argument of a method should be named 'self'
Please fix the code style issue.
```

This is related due to missing exceptions in:

image

https://github.com/keras-team/keras-tuner/blob/41693aacd4440faacca4165e4d15cde53d5570cc/setup.cfg#LL31-L47C9

Moreover, it might be a good idea to refactor the code partially. Like

```python
    def to_proto(status):
        ts = keras_tuner_pb2.TrialStatus
```

becomes

```python
    @staticmethod
    def to_proto(status):
        ts = keras_tuner_pb2.TrialStatus
```

**To Reproduce**

```shell
 flake8 .
```
provides:

```output
./keras_tuner/tuners/sklearn_tuner.py:139:23: N803 argument name 'X' should be lowercase
./keras_tuner/tuners/sklearn_tuner.py:154:33: N803 argument name 'X' should be lowercase
./keras_tuner/tuners/sklearn_tuner.py:160:14: N806 variable 'X_train' in function should be lowercase
./keras_tuner/tuners/sklearn_tuner.py:162:14: N806 variable 'X_test' in function should be lowercase
./keras_tuner/engine/trial.py:46:19: N805 first argument of a method should be named 'self'
./keras_tuner/engine/trial.py:65:21: N805 first argument of a method should be named 'self'
./keras_tuner/engine/conditions.py:63:21: N804 first argument of a classmethod should be named 'cls'
```

**Expected behavior**

```shell
 flake8 .
```

provides:

```output
```

**Additional context**

Currently fixes: #777 

**Would you like to help us fix it?**

### PR DESCRIPTION
**Pull request by Anselmoo**
Fixes #778 issues with `setup.cfg`.

1. Add `staticmethod`
2.  Fix in `@classmethod`
3. Add `pep8-naming`-exceptions back for `sklearn`

### CODE REVIEW

**Review by haifeng-jin — COMMENTED** [review]
Thanks for the PR! I cannot reproduce the flake8 errors on master. Can you reproduce it in the Codespace environment?

**Comment by haifeng-jin** [comment]
May be using `flake8 --version` to print the version and plugins for comparison.
Here is mine:
`6.0.0 (mccabe: 0.7.0, pycodestyle: 2.10.0, pyflakes: 3.0.1) CPython 3.8.15 on Linux`

**Comment by Anselmoo** [comment]
> May be using `flake8 --version` to print the version and plugins for comparison.
> Here is mine:
> `6.0.0 (mccabe: 0.7.0, pycodestyle: 2.10.0, pyflakes: 3.0.1) CPython 3.8.15 on Linux`

That's exactly the problem ... and _sorry_

#### Code Space

```shell
6.0.0 (mccabe: 0.7.0, pycodestyle: 2.10.0, pyflakes: 3.0.1) CPython 3.8.15 on Linux
```

#### Locally via `pyenv 3.10.6:miniconda3-latest`

```shell
4.0.1 (mccabe: 0.6.1, naming: 0.10.0, pycodestyle: 2.8.0, pyflakes: 2.4.0) CPython 3.10.6 on Darwin
```

Maybe make a `requirements-dev.txt` sense?

**Comment by Anselmoo** [comment]
> @Anselmoo I guess it is the `naming` package is making the difference.
> Everything that required for dev is managed by the `setup.py` file.
> So would you please update the PR by adding the `naming` package to `setup.py` (in the `"tests"` section)?

I am not sure if this https://pypi.org/project/naming/ should be added? 

However, it was my fault for _incorrectly_ installing it, therefore I add a comment in the **contributor notes**.

**Review by haifeng-jin — APPROVED** [review]

**Pull request merged**
