### PR TITLE
Added CI for windows.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
For this to work, I believe a project collaborator must click on the tab "Actions" and enable Github actions.

The support for windows on travis CI isn't very good. This is why I picked github actions for running the windows build. Similarly to travis, we won't pay as we're on the open source plan.

I also fixed the docs tests to make the windows CI work. 

On my fork, the windows test is passing. See the logs here: https://github.com/gabrieldemarmiesse/keras-tuner/commit/cf2dc1938efe8e35e82c97ba76daf95cfcb8ae38/checks?check_suite_id=365260325

### CODE REVIEW

**Comment by omalleyt12** [comment]
@gabrieldemarmiesse Thanks for the PR! Can you provide more context on GH actions / how this changes our CI? I'm not familiar with it

**Comment by gabrieldemarmiesse** [comment]
It will add a second CI and we'll have both running at the same time when a PR is opened. It's very similar to travis ci. The functionalities are practically the same. It's free for open source projects. I didn't take travis because the windows tests it didn't fit in the matrix and I had a bit more difficulties making the tests work for windows in travis. If you wish to do so, I can implement everything on travis. 

One benefit we have from using multiple CI is that they all run in parrallel and we have then ~10 jobs running at the same time in total.

Keras-autodoc uses github actions if you want to take a look: https://github.com/keras-team/keras-autodoc/commits/master

**Comment by gabrieldemarmiesse** [comment]
Actually I checked in github action will be enable when the first github actions file is commited to a branch of the repo.

**Comment by omalleyt12** [comment]
Sounds good to me, thanks for explaining and thanks for doing this!

**Pull request merged**
