### PR TITLE
Generate samples based on seed and update gaussian kernel

### PR DESCRIPTION
**Pull request by themrzmaster**
Generate random samples based on inpu seed

### CODE REVIEW

**Comment by omalleyt12** [comment]
Closed / reopened for build flake

**Comment by omalleyt12** [comment]
@themrzmaster Can you please add a comment here when the PR is ready for review again? Dropping approval for now so I don't accidentally merge while you are working on it

**Comment by themrzmaster** [comment]
It's ready! sorry for the many commits.

**Comment by omalleyt12** [comment]
@themrzmaster Great thanks, no worries! Could you explain the use of `nu=2.5` in the Matern kernel? It looks like it is optimizing well, I am just curious for the reason for this change. Do you expect this to perform better than the default setting for the general case?

**Comment by themrzmaster** [comment]
As proposed in http://papers.nips.cc/paper/4522-practical-bayesian-optimization-of-machine-learning-algorithms.pdf , the matern kernel with a 2.5 nu value results in sample functions which are twice-differentiable, which works better for quasi newton optimization algorithms as the one used (L-BFGS)

**Comment by omalleyt12** [comment]
> @omalleyt12 As proposed in http://papers.nips.cc/paper/4522-practical-bayesian-optimization-of-machine-learning-algorithms.pdf , the matern kernel with a 2.5 nu value results in sample functions which are twice-differentiable, which works better for quasi newton optimization algorithms as the one used (L-BFGS)

Great, sounds good to me! Thanks for looking into this, merging now

**Pull request merged**
